server:
  port: 8099
spring:
  application:
    name: rs01
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/study?serverTimezone=GMT%2B8&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: 654321
  redis:
    database: 4
    host: 127.0.0.1
    password: 123456
    port: 6379
    timeout: 3000ms
swagger:
  production: true